version: 0.2
 
phases:
  install:
    commands:
      - |
        echo "Build & Test started on `date`"
        echo `uname -a`
        echo `node --version`
        echo `aws --version`
        cd continuous-deploy-01
        npm install
  pre_build:
    commands:
      - |
        echo "Nothing to do in the pre_build phase..."
  build:
    commands:
      - |
        for template in infra/src/cft/*.yml; do
          echo "$template" | xargs -I% -t aws cloudformation validate-template --template-body file://%
        done
        for template in infra/src/cft/*.yml; do
          echo $template
          ./node_modules/.bin/cfn-lint validate $template
        done
  post_build:
    commands:
      - |
        echo "Nothing to do in the post_build phase..."
        echo "Build & Test completed on `date`"
artifacts:
  files:
    - '**/*'
