AWSTemplateFormatVersion: "2010-09-09"
Description: "Artifact Repository for CFn Continuous Delivery Example"
Resources:
  ArtifactStore:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "BucketOwnerFullControl"
Outputs:
  ArtifactStoreName:
    Description: "Name of Artifact Repository"
    Value: !Ref ArtifactStore
