AWSTemplateFormatVersion: "2010-09-09"
Description: "Root Stack"
Parameters:
  StackIdentifier:
    Type: "String"
    Description: "Stack Identifier"
    Default: "mastering-cfn-continuous-deploy-01"
Mappings:
  CONSTRAINTS:
    STACK:
      BUCKETNAME: "ignite-cfn-template-store3"
      TIMEOUT: 5
    CFN-TEMPLATE:
      ARTIFACTREPOSITORY: "examples/mastering-cfn/continuous-deploy-01/pipeline/src/cft/artifact-repository.yml"
      ORCHESTRATION: "examples/mastering-cfn/continuous-deploy-01/pipeline/src/cft/pipeline.yml"
      BUILD: "examples/mastering-cfn/continuous-deploy-01/pipeline/src/cft/build.yml"
    CODEBUILD:
      PROJECTNAME: "mastering-cfn-continuous-deploy-01-pj"
Resources:
  ArtifactRepository:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3.amazonaws.com/${BucketName}/${TemplatePath}"
          - {
              BucketName: !FindInMap [ CONSTRAINTS, STACK, BUCKETNAME ],
              TemplatePath: !FindInMap [ CONSTRAINTS, CFN-TEMPLATE, ARTIFACTREPOSITORY ]
            }
      TimeoutInMinutes: !FindInMap [ CONSTRAINTS, STACK, TIMEOUT]
  Build:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3.amazonaws.com/${BucketName}/${TemplatePath}"
          - {
              BucketName: !FindInMap [ CONSTRAINTS, STACK, BUCKETNAME ],
              TemplatePath: !FindInMap [ CONSTRAINTS, CFN-TEMPLATE, BUILD ]
            }
      TimeoutInMinutes: !FindInMap [ CONSTRAINTS, STACK, TIMEOUT ]
      Parameters:
        Identifier: !Ref StackIdentifier
        CodeBuildProjectName: !FindInMap [ CONSTRAINTS, CODEBUILD, PROJECTNAME ]
  Pipeline:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3.amazonaws.com/${BucketName}/${TemplatePath}"
          - {
              BucketName: !FindInMap [ CONSTRAINTS, STACK, BUCKETNAME ],
              TemplatePath: !FindInMap [ CONSTRAINTS, CFN-TEMPLATE, ORCHESTRATION ]
            }
      TimeoutInMinutes: !FindInMap [ CONSTRAINTS, STACK, TIMEOUT ]
      Parameters:
        CodeBuildProjectName: !FindInMap [ CONSTRAINTS, CODEBUILD, PROJECTNAME ]
        ArtifactBucketName: !GetAtt [ ArtifactRepository, Outputs.ArtifactRepositoryName ]
