AWSTemplateFormatVersion: "2010-09-09"
Description: "Source Code Repository Resources for exercise10"
Parameters:
  ParentStackName:
    Description: "Parent Stack Name for This Stack Resources"
    Type: "String"
Resources:
  CodeCommitRepository:
    Type: "AWS::CodeCommit::Repository"
    Properties:
      RepositoryDescription: "Source Code Repository for Web Application PoC."
      RepositoryName: !Ref ParentStackName
Outputs:
  Name:
    Description: "The Name for source code repository"
    Value: !GetAtt CodeCommitRepository.Name
  CloneUrlHTTPS:
    Description: "The URL to use for cloning the repository over HTTPS"
    Value: !GetAtt CodeCommitRepository.CloneUrlHttp
  CloneUrlSSH:
    Description: "The URL to use for cloning the repository over SSH"
    Value: !GetAtt CodeCommitRepository.CloneUrlSsh